version: 2

sources:
  - name: operacion 
    schema: OPERACION
    database: pasaporcaja
    tables: 
      - name: SCRAPINGS
        identifier: SCRAPINGS_*
      - name: RETAILS
      - name: DELIVERY_SKU
      - name: MATCHS
      - name: VISITAS
  - name: comercial
    schema: COMERCIAL
    database: pasaporcaja
    tables:
      - name: PRODUCT_DETAILS
      - name: NIVEL_0
      - name: SELLERS_ID
      - name: SELLERS
  - name: femsa
    schema: FEMSA
    database: pasaporcaja
    tables:
      - name: MATCHS_DASHBOARD
